# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliate_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='ad_space',
            field=models.IntegerField(unique=True),
        ),
    ]
