# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
    ]
