# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_auto_20170122_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_type', models.CharField(blank=True, max_length=300)),
                ('domains', models.CharField(blank=True, max_length=100)),
                ('is_legal', models.BooleanField(default=None)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('mediums', models.CharField(blank=True, max_length=300)),
                ('categories', models.CharField(blank=True, max_length=300)),
                ('traffic', models.CharField(blank=True, max_length=300)),
                ('visitors', models.IntegerField(blank=True)),
                ('product_feed', models.BooleanField()),
                ('feed_fields', models.CharField(blank=True, max_length=300)),
                ('insertion_order', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('tax_id', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('legal_rep', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('fiscal_add', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('bank_st', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('Constitutive', models.FileField(blank=True, upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
