# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Constitutive',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='affiliate_type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='bank_st',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='categories',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='domains',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='information',
            name='feed_fields',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='fiscal_add',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='insertion_order',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='legal_rep',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='mediums',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='tax_id',
            field=models.FileField(upload_to='/home/ulises/Linio/django/env/skunk/affiliates/uploads/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='traffic',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='information',
            name='visitors',
            field=models.IntegerField(choices=[(1000, 'Less than 1000'), (5000, '1000 - 10,000'), (50000, '10,000 - 100,000'), (100000, 'More than 100,000')]),
        ),
    ]
